version: '3.7'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-file: "10"
    max-size: "1M"

networks:
  default:
    name: icinga

services:
  # The Icinga 2 docker image does not support configuration via env vars at the moment.
  # So, we have to ship some configs with this little init container. Referenced in depends_on of the icinga2 service.
  # REFACT change deployment so the init container is not needed anymore
  init-icinga2:
    # see https://github.com/Icinga/docker-icinga2
    image: icinga/icinga2:master
    command: [ "/config/init-icinga2.sh" ]
    hostname: ${ICINGA_HOST}
    domainname: ${ICINGA_DOMAIN}
    environment:
      ICINGA_MASTER: 1
      HOST_NAME: icinga2
      ICINGA_CN: ${ICINGA_DOMAIN}
    logging: *default-logging
    volumes:
      - ./icinga2:/data
      - ./icingadb.conf:/config/icingadb.conf
      - ./icingaweb-api-user.conf:/config/icingaweb-api-user.conf
      - ./init-icinga2.sh:/config/init-icinga2.sh

  icinga2:
    # see https://github.com/Icinga/docker-icinga2
    # see https://hub.docker.com/r/icinga/icinga2
    image: icinga/icinga2:master
    depends_on:
      - redis
      - init-icinga2
    hostname: ${ICINGA_HOST}
    domainname: ${ICINGA_DOMAIN}
    environment:
      ICINGA_MASTER: 1
      HOST_NAME: icinga2
      ICINGA_CN: ${ICINGA_DOMAIN}
      # ICINGA_ZONE=master
    logging: *default-logging
    ports:
      - 5665:5665 # REFACT consider to un-expose this, as it is not needed for the deployment AFAIK
    volumes:
      - ./icinga2:/data
      - ./msmtp.conf:/etc/msmtprc:ro
      - ./icinga2/home:/home:ro

  icingadb:
    # See https://github.com/Icinga/docker-icingadb
    image: icinga/icingadb:master
    depends_on:
      - mysql
      - redis
    environment:
      ICINGADB_REDIS_ADDRESS: redis:6379
      ICINGADB_REDIS_PASSWORD: ""
      
      ICINGADB_DATABASE_HOST: mysql
      ICINGADB_DATABASE_PORT: 3306
      
      ICINGADB_DATABASE_DATABASE: icingadb
      ICINGADB_DATABASE_USER: icingadb
      ICINGADB_DATABASE_PASSWORD: ${ICINGADB_MYSQL_PASSWORD}
    logging: *default-logging
    # Restart Icinga DB container automatically since we have to wait for the database to be ready.
    # Please note that this needs a more sophisticated solution.
    restart: unless-stopped

  icingaweb:
    # see https://github.com/Icinga/docker-icingaweb2
    # TODO switch to :master asap. But right now that fails, as some dependencies are not in place
    # Master would allow to test display of check commands, but can't have that yet
    # if :master is broken :latest should still work (but doesn't contain the enhanced object introspection)
    image: icinga/icingaweb2:master
    depends_on:
      - mysql
      - redis
    environment:
      icingaweb.enabledModules: icingadb,ipl
      icingaweb.passwords.icingaweb2.icingaadmin: ${ICINGAWEB_ADMIN_PASSWORD}
      
      icingaweb.authentication.icingaweb2.backend: db
      icingaweb.authentication.icingaweb2.resource: icingaweb_db
      
      icingaweb.config.global.config_backend: db
      icingaweb.config.global.config_resource: icingaweb_db
      icingaweb.config.logging.log: php
      
      icingaweb.groups.icingaweb2.backend: db
      icingaweb.groups.icingaweb2.resource: icingaweb_db
      
      icingaweb.modules.icingadb.config.icingadb.resource: icingadb
      icingaweb.modules.icingadb.config.redis1.host: redis
      icingaweb.modules.icingadb.config.redis1.port: 6379
      
      # new config? https://github.com/Icinga/docker-icingaweb2/issues/65
      icingaweb.modules.icingadb.redis.redis1.host: redis
      icingaweb.modules.icingadb.redis.redis1.port: 6379
      
      icingaweb.modules.monitoring.commandtransports.icinga2.transport: api
      icingaweb.modules.monitoring.commandtransports.icinga2.host: icinga2
      icingaweb.modules.monitoring.commandtransports.icinga2.username: icingaweb
      icingaweb.modules.monitoring.commandtransports.icinga2.password: ${ICINGAWEB_ICINGA2_API_USER_PASSWORD}
      
      # new config? https://github.com/Icinga/docker-icingaweb2/issues/65
      icingaweb.modules.icingadb.commandtransports.icinga2.transport: api
      icingaweb.modules.icingadb.commandtransports.icinga2.host: icinga2
      icingaweb.modules.icingadb.commandtransports.icinga2.port: 5665
      icingaweb.modules.icingadb.commandtransports.icinga2.username: icingaweb
      icingaweb.modules.icingadb.commandtransports.icinga2.password: ${ICINGAWEB_ICINGA2_API_USER_PASSWORD}
      
      icingaweb.resources.icingaweb_db.type: db
      icingaweb.resources.icingaweb_db.db: mysql
      icingaweb.resources.icingaweb_db.host: mysql
      icingaweb.resources.icingaweb_db.dbname: icingaweb
      icingaweb.resources.icingaweb_db.username: icingaweb
      icingaweb.resources.icingaweb_db.password: ${ICINGAWEB_MYSQL_PASSWORD}
      icingaweb.resources.icingaweb_db.charset: utf8mb4
      
      icingaweb.resources.icingadb.type: db
      icingaweb.resources.icingadb.db: mysql
      icingaweb.resources.icingadb.host: mysql
      icingaweb.resources.icingadb.dbname: icingadb
      icingaweb.resources.icingadb.username: icingadb
      icingaweb.resources.icingadb.password: ${ICINGADB_MYSQL_PASSWORD}
      icingaweb.resources.icingadb.charset: utf8mb4
      
      icingaweb.roles.Administrators.users: icingaadmin
      icingaweb.roles.Administrators.permissions: '*'
      icingaweb.roles.Administrators.groups: Administrators
    logging: *default-logging
    ports:
      - 8080:8080
    # Restart Icinga Web container automatically since we have to wait for the database to be ready.
    # Please note that this needs a more sophisticated solution.
    restart: unless-stopped
    volumes:
      - ./icingaweb:/data

  redis:
    image: redis
    logging: *default-logging
  
  # REFACT rename mariadb? But this is replicated quite some places that need to update too
  mysql:
    # see https://hub.docker.com/_/mariadb
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      ICINGAWEB_MYSQL_PASSWORD: ${ICINGAWEB_MYSQL_PASSWORD}
      ICINGADB_MYSQL_PASSWORD: ${ICINGADB_MYSQL_PASSWORD}
    logging: *default-logging
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init-mysql.sh:/docker-entrypoint-initdb.d/init-mysql.sh
